### ISSUE TITLE
Probes inserted is always 0

### ISSUE THREAD

**Issue by ksfasf** [PatrikAAberg/dmce#11]
I'm unable to insert any probes, following the below steps.

Why is it reporting 'Probes inserted: 0'?

This looks like some very promising work.

Is there a FAQ or support community behind this project?

Thanks,
ksfasf

1) git clone https://github.com/nyuwireless-unipd/ns3-mmwave.git
2) dmce-set-profile -v coverage -i sw/mmwave/examples
3) dmce-launcher -n 2 --progress 
|. . . . . . . . . . . . . . . >|
|. . . . . . . . . . . . . . . >|
===============================================
git repository                    /home/dng/ns3-mmwave
Old SHA-1                         0e8842fa (0e8842fa0538a86296532d46dc73059108534b16)
New SHA-1                         HEAD     (a402f10160a84d1901145fbcbffc39123ed23ad7)
Files examined                    11
Files probed                      0
Files skipped                     11
Probes inserted                   0
DMCE version                      1.7-1
===============================================
done: real: 0m9.113s user: 0m27.398s sys: 0m1.470s

**Comment by RMPers** [comment]
Have you tried dmce-launcher -aq ? (-n 2 only probes the last patch plus whatever is modified/untracked)

**Comment by ksfasf** [comment]
No, I didn't want to add probes to the entire codebase. I was assuming that 11 source files would have been enough for at least 1 probe to be added. What prevents probes from being added?

Anyway, I tried it and I still got 0 probes inserted (also I fixed a typo in my dmce-set-profile command):

dmce-set-profile -v coverage -i src/mmwave/examples
Updated config file: /home/dng/.dmceconfig
Profile: coverage
Excluded files and/or functions:
['do-not-exclude-anything']
Included files and/or functions:
['src/mmwave/examples']
Excluded constructs (textual search):
[]

dmce-launcher -aq
===============================================
git repository                    /home/dng/ns3-mmwave
Old SHA-1                         7a0eab74 (7a0eab742410f9519e557d8a5142454ca46a29c3)
New SHA-1                         HEAD     (a402f10160a84d1901145fbcbffc39123ed23ad7)
Files examined                    18
Files probed                      0
Files skipped                     18
Probes inserted                   0
DMCE version                      1.7-1
===============================================
done: real: 4m15.825s user: 27m46.945s sys: 0m33.066s

**Comment by PatrikAAberg** [comment]
Hi,

At some point, the .cc extension was apparently lost in the parser. It is now fixed and should be able to use the v1.7.2 deb release.

For the ns3-mmwave git I now got around 30k probes using -a, and 4 probes for the last commit (-n 2).
 
Big thanks for reporting!

**Comment by ksfasf** [comment]
Glad to help, thanks for fixing the issue. 👍 

dmce-launcher -n 2 --progress
|. . . . . . . . . . . . . . . >|
|. . . . . . . . . . . . . . . >|
===============================================
git repository                    /home/dng/ns3-mmwave
Old SHA-1                         0e8842fa (0e8842fa0538a86296532d46dc73059108534b16)
New SHA-1                         HEAD     (a402f10160a84d1901145fbcbffc39123ed23ad7)
Files examined                    11
Files probed                      8
Files skipped                     3
Probes inserted                   32
Probe metadata                    /tmp/dng/dmce/ns3-mmwave/probe-references.log
Probe metadata (original files)   /tmp/dng/dmce/ns3-mmwave/probe-references-original.log
Expressions                       /tmp/dng/dmce/ns3-mmwave/expr-references.log
DMCE version                      1.7-2
===============================================
done: real: 0m20.984s user: 1m50.687s sys: 0m4.611s
