### ISSUE TITLE
Can execution time be reduced?

### ISSUE THREAD

**Issue by ksfasf** [PatrikAAberg/dmce#12]
Regarding [this execution](https://github.com/PatrikAAberg/dmce/issues/11#issuecomment-1318660342), the time taken for the command to return control of the interactive shell was around 2 minutes for 32 probes. 

Can this elapsed time be reduced?

**Comment by PatrikAAberg** [comment]
Thank you for pointing that out. The copying of include files now (803ab8e5508acdee4d81a9fb6e73ab64ce1267ba) executes much faster. If you have not already noticed, you can build the .deb package executing the "build-deb" script and try it out.

**Comment by ksfasf** [comment]
Definitely much faster, thanks! It took 43 seconds to return control back to the interactive shell. Previously, it took about 2 minutes (maybe more).

dmce-launcher -n 2 --progress
|. . . . . . . . . . . . . . . >|
|. . . . . . . . . . . . . . . >|
===============================================
git repository                    /home/dng/ns3-mmwave
Old SHA-1                         0e8842fa (0e8842fa0538a86296532d46dc73059108534b16)
New SHA-1                         HEAD     (a402f10160a84d1901145fbcbffc39123ed23ad7)
Files examined                    11
Files probed                      8
Files skipped                     3
Probes inserted                   32
Probe metadata                    /tmp/dng/dmce/ns3-mmwave/probe-references.log
Probe metadata (original files)   /tmp/dng/dmce/ns3-mmwave/probe-references-original.log
Expressions                       /tmp/dng/dmce/ns3-mmwave/expr-references.log
DMCE version                      1.7-3
===============================================
done: real: 0m21.809s user: 1m55.303s sys: 0m5.182s
