### ISSUE TITLE
DMCE_PROBE instrumentation not semantics-preserving in logical expression with negated lhs

### ISSUE THREAD

**Issue by creichen** [PatrikAAberg/dmce#17]
OpenJDK 11u, `2c47c45f0747e86a3b97384bea48107627ffd040`:

Instrumenting the following line `102` in `src/hotspot/share/oops/objArrayKlass.cpp`:

```c++
  if (!element_klass->is_instance_klass() ||
      (name = InstanceKlass::cast(element_klass)->array_name()) == NULL) {
```

leads to the semantically different code below:

```c++
  if (!(DMCE_PROBE(25201), element_klass->is_instance_klass() ||
      (name = InstanceKlass::cast(element_klass)->array_name()) == NULL)) {
```

Ignoring the DMCE_PROBE(), the code above replaces `(!a || b)` by `(!(a || b))`, i.e., it negates the entire disjunction rather than just the left-hand side of the `||`.

A semantics-preserving replacement would be:

```c++
  if (DMCE_PROBE(25201), !element_klass->is_instance_klass() ||
    (name = InstanceKlass::cast(element_klass)->array_name()) == NULL) {
```

which works as intended.

**Comment by PatrikAAberg** [comment]
That's how you write a bug report. :) Big thanks!

This problem should now be fixed in 60d68add33c08d8a11e4b017378ce49b07f1f36f which is part of the 1.7-4 release.
