### ISSUE TITLE
No feedback when running in non-repository directories

### ISSUE THREAD

**Issue by IIAndreasII** [PatrikAAberg/dmce#19]
Currently, when running dmce in a directory that does not contain a git repository, the user is not given any information about the execution:
```
not/a/repo$ dmce
not/a/repo$
```
Proposed output:
```
not/a/repo$ dmce
error: current directory does not contain a git repository
not/a/repo$
```

**Comment by PatrikAAberg** [comment]
Thank you for report and fix! Your patch is merged as commit b9b1f1b643d8ed1fdf185c51b86b4b7b3eda6bbf
