### ISSUE TITLE
Invalid regex matching

### ISSUE THREAD

**Issue by wolverine2k** [PatrikAAberg/dmce#3]
The regex expression used in print_summary.py for checking whether a probe is executed or not can also match output errors from the compiler. A proper regex should check if a probe number is printed instead.

i.e. 

.*DMCE_PROBE\((.*)\).* should be .*DMCE_PROBE\((\d+)\).*

I am providing a PR for the same.

**Comment by PatrikAAberg** [comment]
I agree on the regexp being more precise. That said, I do not understand how you get to the point where you feed compiler output to this script. Could you please explain your execution flow?

Kind Regards,
Patrik

**Comment by wolverine2k** [comment]
The compiler output is a part of the console log output. We just send the whole console log output from the executing test to the print summary script. Hence any compiler errors and/or lint info/warnings (even if suppressed) will be a part of the console output. And no, there is no way to differentiate between outputs from various tests.

The change makes the regex tighter and suitable to be used across all console logs irrespective of whether the output is from a compiler run or an actual test run.

BR; Naresh

**Comment by PatrikAAberg** [comment]
Ah, ok. Your patch is merged into master.

However, I strongly suggest you separate the testlog from the rest. Otherwise I suspect you will fall on more hurdles and end up in some time-consuming state-driven text parsing. :)

Good luck with your tests!

Kind Regards,
Patrik
